// Generated by TransPyC
#include <stdio.h>

#define MAX_VALUE 100
#define PI 3.14159

static int global_var = 42;

struct Point {
};

int TestStruct() {
    struct Point p;
    p->x = 10;
    p->y = 20;
    return p->x + p->y;
}

int TestPointer() {
    void *addr = ((void *)4096);
    int value = 42;
    void *ptr = addr;
    *((void *)ptr) = value;
    return *((void *)ptr);
}

int Add(int a, int b) {
    return a + b;
}

int TestIf(int x) {
    if (x > 0) {
        return x + 1;
    } else if (x < 0) {
        return x - 1;
    } else {
        return 0;
    }
}

int TestLoop() {
    int sum = 0;
    for (int i = 0; i < 10; i++) {
        sum += i;
    }
    return sum;
}

void TestAsm() {
    asm volatile (
    movb $0x0e, %%ah
    int $0x10
    : : "a"(c)
    );
}

int TestTypeCast() {
    int x = 42;
    float y = ((float)x);
    return y;
}

int main() {
    printf("TestStruct: %d\n", TestStruct());
    printf("TestPointer: %d\n", TestPointer());
    printf("Add: %d\n", Add(10, 20));
    printf("TestIf: %d\n", TestIf(5));
    printf("TestLoop: %d\n", TestLoop());
    printf("TestTypeCast: %f\n", TestTypeCast());
    TestAsm();
    return 0;
}
