// Generated by TransPyC
#include <stdio.h> // import stdio
int global_var = 42;
void TestMacro() {
#define MAX_VALUE 100
#define PI 3.14159
}
void TestStruct() {
struct Point {
};
int p = Point();
p->x = 10;
p->y = 20;
return (p->x + p->y);
}
void TestPointer() {
int addr = ((void *)4096);
int value = 42;
int ptr = addr;
*((void *)ptr) = value;
return 0;
}
void Add(int a, int b) {
return (a + b);
}
void TestIf(int x) {
if ((x > 0)) {
return (x + 1);
}
else {
if ((x < 0)) {
return (x - 1);
}
else {
return 0;
}
}
}
void TestLoop() {
int sum = 0;
for (...) {
}
return sum;
}
void TestAsm() {
asm volatile (
    movb $0x0e, %%ah
    int $0x10
    : : "a"(c)
    );
}
void TestTypeCast() {
int x = 42;
int y = ((float)x);
return y;
}