# Generated by TransPyC
import c
import t
import stdio  # #include <stdio.h>
MAX_VALUE = 100  # #define MAX_VALUE 100
PI = 3.14159  # #define PI 3.14159
global_var = 42 // static int global_var = 42
class Point: // struct Point {
# p->x = 10;
# p->y = 20;
# return p->x + p->y;
# void *addr = ((void *)4096);
value = 42 // int value = 42
# void *ptr = addr;
# *((void *)ptr) = value;
# return *((void *)ptr);
# return a + b;
# if (x > 0) {
# return x + 1;
# return x - 1;
# return 0;
sum = 0 // int sum = 0
# for (int i = 0; i < 10; i++) {
# sum += i;
# return sum;
def TestAsm(): // void TestAsm() {
x = 42 // int x = 42
y = ((float)x) // float y = ((float)x)
# return y;
# return 0;