// Generated by TransPyC
#include <stdio.h>
#include "lib.includes.c.h"
#include "lib.includes.t.h"
struct Person {
    char* name;
    int age;
};
int add(int a, int b) {
    return (a + b);
}
void Person____init__(struct Person* self, char* name, int age) {
    self.name = name;
    self.age = age;
}
void Person__greet(struct Person* self) {
    printf("%d
", 0);
}
int main(void) {
    int result = add(5, 3);
    printf("%d
", 0);
    int p = Person("Alice", 30);
    p__greet(&p);
    return 0;
}