// Generated by TransPyC
struct BOOTINFO {
    char cyls;
    char leds;
    char vmode;
    char reserve;
    short scrnx;
    short scrny;
    char* vram;
};
#define ADR_BOOTINFO 4080
#define ADR_DISKIMG 1048576
struct FIFO32 {
    int* buf;
    int p;
    int q;
    int size;
    int free;
    int flags;
    struct TASK* task;
};
#define COL8_000000 0
#define COL8_FF0000 1
#define COL8_00FF00 2
#define COL8_FFFF00 3
#define COL8_0000FF 4
#define COL8_FF00FF 5
#define COL8_00FFFF 6
#define COL8_FFFFFF 7
#define COL8_C6C6C6 8
#define COL8_840000 9
#define COL8_008400 10
#define COL8_848400 11
#define COL8_000084 12
#define COL8_840084 13
#define COL8_008484 14
#define COL8_848484 15
#define COL8_202020 16
#define COL8_RWL 16
#define COL8_252525 17
struct DLL_STRPICENV {
    int work[((64 * 1024) / 4)];
};
struct RGB {
    unsigned char b;
    unsigned char g;
    unsigned char r;
    unsigned char t;
};
struct SEGMENT_DESCRIPTOR {
    short limit_low;
    short base_low;
    char base_mid;
    char access_right;
    char limit_high;
    char base_high;
};
struct GATE_DESCRIPTOR {
    short offset_low;
    short selector;
    char dw_count;
    char access_right;
    short offset_high;
};
#define ADR_IDT 2553856
#define LIMIT_IDT 2047
#define ADR_GDT 2555904
#define LIMIT_GDT 65535
#define ADR_BOTPAK 2621440
#define LIMIT_BOTPAK 524287
#define AR_DATA32_RW 16530
#define AR_CODE32_ER 16538
#define AR_LDT 130
#define AR_TSS32 137
#define AR_INTGATE32 142
#define PIC0_ICW1 32
#define PIC0_OCW2 32
#define PIC0_IMR 33
#define PIC0_ICW2 33
#define PIC0_ICW3 33
#define PIC0_ICW4 33
#define PIC1_ICW1 160
#define PIC1_OCW2 160
#define PIC1_IMR 161
#define PIC1_ICW2 161
#define PIC1_ICW3 161
#define PIC1_ICW4 161
#define PORT_KEYDAT 96
#define PORT_KEYCMD 100
struct MOUSE_DEC {
    unsigned char buf[3];
    char phase;
    int x;
    int y;
    int btn;
};
#define MEMMAN_FREES 4090
#define MEMMAN_ADDR 3932160
struct FREEINFO {
    unsigned int addr;
    unsigned int size;
};
struct MEMMAN {
    int frees;
    int maxfrees;
    int lostsize;
    int losts;
    struct FREEINFO free[MEMMAN_FREES];
};
#define MAX_SHEETS 256
struct SHEET {
    unsigned char* buf;
    int bxsize;
    int bysize;
    int vx0;
    int vy0;
    int col_inv;
    int height;
    int flags;
    struct SHTCTL* ctl;
    struct TASK* task;
};
struct SHTCTL {
    unsigned char* vram;
    unsigned char* map;
    int xsize;
    int ysize;
    int top;
    struct SHEET *sheets[MAX_SHEETS];
    struct SHEET sheets0[MAX_SHEETS];
};
#define MAX_TIMER 500
struct TIMER {
    struct TIMER* next;
    unsigned int timeout;
    char flags;
    char flags2;
    struct FIFO32* fifo;
    int data;
};
struct TIMERCTL {
    unsigned int count;
    unsigned int next;
    struct TIMER* t0;
    struct TIMER timers0[MAX_TIMER];
};
extern struct TIMERCTL timerctl;
#define MAX_TASKS 1000
#define TASK_GDT0 3
#define MAX_TASKS_LV 100
#define MAX_TASKLEVELS 10
struct TSS32 {
    int backlink;
    int esp0;
    int ss0;
    int esp1;
    int ss1;
    int esp2;
    int ss2;
    int cr3;
    int eip;
    int eflags;
    int eax;
    int ecx;
    int edx;
    int ebx;
    int esp;
    int ebp;
    int esi;
    int edi;
    int es;
    int cs;
    int ss;
    int ds;
    int fs;
    int gs;
    int ldtr;
    int iomap;
};
struct TASK {
    int sel;
    int flags;
    int level;
    int priority;
    struct FIFO32 fifo;
    struct TSS32 tss;
    struct SEGMENT_DESCRIPTOR ldt[2];
    struct CONSOLE* cons;
    int ds_base;
    int cons_stack;
    struct FILEHANDLE* fhandle;
    int* fat;
    char* cmdline;
    unsigned char langmode;
    unsigned char langbyte1;
};
struct TASKLEVEL {
    int running;
    int now;
    struct TASK *tasks[MAX_TASKS_LV];
};
struct TASKCTL {
    int now_lv;
    char lv_change;
    struct TASKLEVEL level[MAX_TASKLEVELS];
    struct TASK tasks0[MAX_TASKS];
};
extern struct TASKCTL* taskctl;
extern struct TIMER* task_timer;
struct CONSOLE {
    struct SHEET* sht;
    int cur_x;
    int cur_y;
    int cur_c;
    struct TIMER* timer;
};
struct FILEHANDLE {
    char* buf;
    int size;
    int pos;
};
struct FILEINFO {
    unsigned char name[8];
    unsigned char ext[3];
    unsigned char type;
    char reserve[10];
    unsigned short time;
    unsigned short date;
    unsigned short clustno;
    unsigned int size;
};
extern int MOUSEX;
extern int MOUSEY;
extern int MOUSEBTN;
extern int mousemode;
extern struct SHEET* sht_back;
extern struct SHEET* sht_mouse;
extern struct BOOTINFO* binfo;
extern struct SHTCTL* shtctl;
extern unsigned int memtotal;
extern struct SHEET* sht_start;
extern unsigned char* buf_start;
extern int sht_start_flan;
extern char* RegistrationCode;
extern struct FILEINFO* finfo;
extern struct SHEET* sht;
extern struct SHEET* key_win;
extern struct SHEET* sht2;
extern struct FIFO32 fifo;
extern struct FIFO32 keycmd;
extern int key_shift;
extern int key_leds;
extern int keycmd_wait;
#define KEYCMD_LED 237
static char keytable0[128];
static char keytable1[128];
#define cmos_index 112
#define cmos_data 113
#define CMOS_CUR_SEC 0
#define CMOS_ALA_SEC 1
#define CMOS_CUR_MIN 2
#define CMOS_ALA_MIN 3
#define CMOS_CUR_HOUR 4
#define CMOS_ALA_HOUR 5
#define CMOS_WEEK_DAY 6
#define CMOS_MON_DAY 7
#define CMOS_CUR_MON 8
#define CMOS_CUR_YEAR 9
#define CMOS_DEV_TYPE 18
#define CMOS_CUR_CEN 50
struct ACPI_RSDP {
    char Signature[8];
    unsigned char Checksum;
    char OEMID[6];
    unsigned char Revision;
    unsigned int RsdtAddress;
    unsigned int Length;
    unsigned int XsdtAddress[2];
    unsigned char ExtendedChecksum;
    unsigned char Reserved[3];
};
struct ACPISDTHeader {
    char Signature[4];
    unsigned int Length;
    unsigned char Revision;
    unsigned char Checksum;
    char OEMID[6];
    char OEMTableID[8];
    unsigned int OEMRevision;
    unsigned int CreatorID;
    unsigned int CreatorRevision;
};
struct ACPI_RSDT {
    struct ACPISDTHeader header;
    unsigned int Entry;
};
struct GenericAddressStructure {
    unsigned char AddressSpace;
    unsigned char BitWidth;
    unsigned char BitOffset;
    unsigned char AccessSize;
    unsigned int Address[2];
};
struct ACPI_FADT {
    struct ACPISDTHeader h;
    unsigned int FirmwareCtrl;
    unsigned int Dsdt;
    unsigned char Reserved;
    unsigned char PreferredPowerManagementProfile;
    unsigned short SCI_Interrupt;
    unsigned int SMI_CommandPort;
    unsigned char AcpiEnable;
    unsigned char AcpiDisable;
    unsigned char S4BIOS_REQ;
    unsigned char PSTATE_Control;
    unsigned int PM1aEventBlock;
    unsigned int PM1bEventBlock;
    unsigned int PM1aControlBlock;
    unsigned int PM1bControlBlock;
    unsigned int PM2ControlBlock;
    unsigned int PMTimerBlock;
    unsigned int GPE0Block;
    unsigned int GPE1Block;
    unsigned char PM1EventLength;
    unsigned char PM1ControlLength;
    unsigned char PM2ControlLength;
    unsigned char PMTimerLength;
    unsigned char GPE0Length;
    unsigned char GPE1Length;
    unsigned char GPE1Base;
    unsigned char CStateControl;
    unsigned short WorstC2Latency;
    unsigned short WorstC3Latency;
    unsigned short FlushSize;
    unsigned short FlushStride;
    unsigned char DutyOffset;
    unsigned char DutyWidth;
    unsigned char DayAlarm;
    unsigned char MonthAlarm;
    unsigned char Century;
    unsigned short BootArchitectureFlags;
    unsigned char Reserved2;
    unsigned int Flags;
    struct GenericAddressStructure ResetReg;
    unsigned char ResetValue;
    unsigned char Reserved3[3];
    unsigned int X_FirmwareControl[2];
    unsigned int X_Dsdt[2];
    struct GenericAddressStructure X_PM1aEventBlock;
    struct GenericAddressStructure X_PM1bEventBlock;
    struct GenericAddressStructure X_PM1aControlBlock;
    struct GenericAddressStructure X_PM1bControlBlock;
    struct GenericAddressStructure X_PM2ControlBlock;
    struct GenericAddressStructure X_PMTimerBlock;
    struct GenericAddressStructure X_GPE0Block;
    struct GenericAddressStructure X_GPE1Block;
};
#define ASCLL 0
#define JAPANSE 1
#define JPEUC 2
#define CHINESE 3
#define MAX_LANGUAGE_NUMBER 10
#define LANGUAGE_NUMBER_NOW 4
extern int languages[MAX_LANGUAGE_NUMBER];
void io_hlt(void);
void io_cli(void);
void io_sti(void);
void io_stihlt(void);
int io_in8(int port);
void io_out8(int port, int data);
int io_load_eflags(void);
void io_store_eflags(int eflags);
void load_gdtr(int limit, int addr);
void load_idtr(int limit, int addr);
int load_cr0(void);
void store_cr0(int cr0);
void load_tr(int tr);
void asm_inthandler0c(void);
void asm_inthandler0d(void);
void asm_inthandler20(void);
void asm_inthandler21(void);
void asm_inthandler2c(void);
unsigned int memtest_sub(unsigned int start, unsigned int end);
void farjmp(int eip, int cs);
void farcall(int eip, int cs);
void asm_exw_api(void);
void start_app(int eip, int cs, int esp, int ds, int* tss_esp0);
void asm_end_app(void);
void fifo32_init(struct FIFO32* fifo, int size, int* buf, struct TASK* task);
int fifo32_put(struct FIFO32* fifo, int data);
int fifo32_get(struct FIFO32* fifo);
int fifo32_status(struct FIFO32* fifo);
void init_color(void);
void set_color(int start, int end, unsigned char* rgb);
void boxfill8(unsigned char* vram, int xsize, unsigned char c, int x0, int y0, int x1, int y1);
void init_desktop(char* vram, int x, int y);
void putfont8(char* vram, int xsize, int x, int y, char c, char* font);
void putfonts8_asc(char* vram, int xsize, int x, int y, char c, unsigned char* s);
void init_mouse_cursor8(char* mouse, char bc);
void init_mouse_pen_cursor8(char* mouse, char bc);
void putblock8_8(char* vram, int vxsize, int pxsize, int pysize, int px0, int py0, char* buf, int bxsize);
int read_picture(int* fat, char* vram, int x, int y);
int info_JPEG(struct DLL_STRPICENV* env, int* info, int size, unsigned char* fp);
int decode0_JPEG(struct DLL_STRPICENV* env, int size, unsigned char* fp, int b_type, unsigned char* buf, int skip);
void init_gdtidt(void);
void set_segmdesc(struct SEGMENT_DESCRIPTOR* sd, unsigned int limit, int base, int ar);
void set_gatedesc(struct GATE_DESCRIPTOR* gd, int offset, int selector, int ar);
void init_pic(void);
void inthandler21(int* esp);
void wait_KBC_sendready(void);
void init_keyboard(struct FIFO32* fifo, int data0);
void inthandler2c(int* esp);
void enable_mouse(struct FIFO32* fifo, int data0, struct MOUSE_DEC* mdec);
int mouse_decode(struct MOUSE_DEC* mdec, unsigned char dat);
unsigned int memtest(unsigned int start, unsigned int end);
void memman_init(struct MEMMAN* man);
unsigned int memman_total(struct MEMMAN* man);
unsigned int memman_alloc(struct MEMMAN* man, unsigned int size);
int memman_free(struct MEMMAN* man, unsigned int addr, unsigned int size);
unsigned int memman_alloc_4k(struct MEMMAN* man, unsigned int size);
int memman_free_4k(struct MEMMAN* man, unsigned int addr, unsigned int size);
struct SHTCTL* shtctl_init(struct MEMMAN* memman, unsigned char* vram, int xsize, int ysize);
struct SHEET* sheet_alloc(struct SHTCTL* ctl);
void sheet_setbuf(struct SHEET* sht, unsigned char* buf, int xsize, int ysize, int col_inv);
void sheet_updown(struct SHEET* sht, int height);
void sheet_refresh(struct SHEET* sht, int bx0, int by0, int bx1, int by1);
void sheet_slide(struct SHEET* sht, int vx0, int vy0);
void sheet_free(struct SHEET* sht);
void init_pit(void);
struct TIMER* timer_alloc(void);
void timer_free(struct TIMER* timer);
void timer_init(struct TIMER* timer, struct FIFO32* fifo, int data);
void timer_settime(struct TIMER* timer, unsigned int timeout);
void inthandler20(int* esp);
int timer_cancel(struct TIMER* timer);
void timer_cancelall(struct FIFO32* fifo);
struct TASK* task_now(void);
struct TASK* task_init(struct MEMMAN* memman);
struct TASK* task_alloc(void);
void task_run(struct TASK* task, int level, int priority);
void task_switch(void);
void task_sleep(struct TASK* task);
void make_window8(unsigned char* buf, int xsize, int ysize, char* title, char act);
void putfonts8_asc_sht(struct SHEET* sht, int x, int y, int c, int b, char* s, int l);
void make_textbox8(struct SHEET* sht, int x0, int y0, int sx, int sy, int c);
void make_wtitle8(unsigned char* buf, int xsize, char* title, char act);
void change_wtitle8(struct SHEET* sht, char act);
void api33_sleep(struct CONSOLE* cons, struct TASK* task, int time);
void console_task(struct SHEET* sheet, int memtotal);
void cons_putchar(struct CONSOLE* cons, int chr, char move);
void cons_newline(struct CONSOLE* cons);
void cons_putstr0(struct CONSOLE* cons, char* s);
void cons_putstr1(struct CONSOLE* cons, char* s, int l);
void cons_runcmd(char* cmdline, struct CONSOLE* cons, int* fat, int memtotal);
void cmd_mem(struct CONSOLE* cons, int memtotal);
void cmd_cls(struct CONSOLE* cons);
void cmd_ls(struct CONSOLE* cons);
void cmd_ver(struct CONSOLE* cons);
void cmd_help(struct CONSOLE* cons);
void cmd_type(struct CONSOLE* cons, int* fat, char* cmdline);
void cmd_dir(struct CONSOLE* cons);
void cmd_reboot(struct CONSOLE* cons);
void cmd_exit(struct CONSOLE* cons, int* fat);
void cmd_start(struct CONSOLE* cons, char* cmdline, int memtotal);
void cmd_ncst(struct CONSOLE* cons, char* cmdline, int memtotal);
int cmd_app(struct CONSOLE* cons, int* fat, char* cmdline);
void cmd_fab(struct CONSOLE* cons, int* fat, char* cmdline);
int* exw_api(int edi, int esi, int ebp, int esp, int ebx, int edx, int ecx, int eax);
int* inthandler0d(int* esp);
int* inthandler0c(int* esp);
void exw_api_linewin(struct SHEET* sht, int x0, int y0, int x1, int y1, int col);
void file_readfat(int* fat, unsigned char* img);
void file_loadfile(int clustno, int size, char* buf, int* fat, char* img);
struct FILEINFO* file_search(char* name, struct FILEINFO* finfo, int max);
char* file_loadfile2(int clustno, int* psize, int* fat);
int tek_getsize(unsigned char* p);
int tek_decomp(unsigned char* p, char* q, int size);
struct TASK* open_constask(struct SHEET* sht, unsigned int memtotal);
struct SHEET* open_console(struct SHTCTL* shtctl, unsigned int memtotal);
#define BCD_HEX(n) ((((n >> 4) * 10) + (n & 15)))
#define BCD_ASCII_first(n) ((((n << 4) >> 4) + 48))
#define BCD_ASCII_S(n) (((n << 4) + 48))
unsigned int get_hour_hex(void);
unsigned int get_min_hex(void);
unsigned int get_sec_hex(void);
unsigned int get_day_of_month(void);
unsigned int get_day_of_week(void);
unsigned int get_mon_hex(void);
unsigned int get_year(void);
void init_acpi(void);
int acpi_shutdown(void);
int win_zonclick(int mdec, int mx, int my, int QX, int QY, int SX, int SY, int flan, struct SHEET* sht);
int win_szonclick(int mdec, int mx, int my, int QX, int QY, int SX, int SY, int flan, struct SHEET* sht);
void init_start(struct SHEET* sht);
void init_startlogo(int b);
int binddmousebox(int mx, int my, int mdec, int QX, int QY, int EX, int EY, int mod);
void language_init(void);