 /*
                  ___         ___     
      ___        /  /\       /  /\    
     /  /\      /  /::\     /  /:/    
    /  /:/     /  /:/\:\   /  /:/     
   /  /:/     /  /:/~/:/  /  /:/  ___ 
  /  /::\    /__/:/ /:/  /__/:/  /  /\
 /__/:/\:\   \  \:\/:/   \  \:\ /  /:/
 \__\/  \:\   \  \::/     \  \:\  /:/ 
      \  \:\   \  \:\      \  \:\/:/  
       \__\/    \  \:\      \  \::/   
                 \__\/       \__\/    
Copyright© GVSDS Team
Actor TermiNexus

*/
// Generated by TransPyC



struct Person {
    char name;
    int age;
};
void Person____init__(struct Person* self, char name, int age) {
self->name = name;
self->age = age;
}
char Person__get_name(struct Person* self) {
return self->name;
}
int Person__get_age(struct Person* self) {
return self->age;
}
void Person____init__(struct Person* self, char name, int age) {
self->name = name;
self->age = age;
}
char Person__get_name(struct Person* self) {
return self->name;
}
int Person__get_age(struct Person* self) {
return self->age;
}
int main() {
int p = Person("Alice", 30);
printf("%d
", p__get_name(&p));
printf("%d
", p__get_age(&p));
return 0;
}