 /*
       ___        ___         ___     
      /  /\      /  /\       /  /\    
     /  /:/     /  /::\     /  /:/    
    /  /:/     /  /:/\:\   /  /:/     
   /  /:/     /  /:/~/:/  /  /:/  ___ 
  /  /::\    /__/:/ /:/  /__/:/  /  /\
 /  /:/\:\   \  \:\/:/   \  \:\ /  /:/
/__/:/  \:\   \  \::/     \  \:\  /:/ 
\__\/ \  \:\   \  \:\      \  \:\/:/  
       \  \:\   \  \:\      \  \::/   
        \__\/    \__\/       \__\/    
Copyright GVSDS Team
Actor TermiNexus 
Generated by TransPyC
*/


#include "../core/kernel.h" // from ..core.kernel import *
#include "../../.UNCADK/stdlib.h"
int MEMMAN_ADDR = 0x003c0000;
struct A {
};
struct SHTCTL {
    struct SHEET *sheets[MAX_SHEETS];
};
struct FILEHANDLE {
    char* buf;
    int size;
    int pos;
};
struct TASK {
    struct FILEHANDLE* fhandle;
    struct FILEHANDLE fhandle2;
};
void init_fpu(void) {
    __asm__ volatile (
        ".intel_syntax noprefix\n\t"
        "mov eax, cr0\n\t"
        "and eax, 0x9ffffff\n\t"
        "mov cr0, eax\n\t"
        "fninit"
    );
}
void sheet_updown(struct SHEET* sht, int height) {
    init_fpu();
    while (1) {
        while (sht->height != height && sht->height != 0) {
            if (sht->height < height) {
                sht->height += 1;
            }
            else {
                sht->height -= 1;
            }
        }
    }
    struct TASK* task;
    if (task->fhandle2.buf == 0) {
        task->fhandle2.buf = 0;
    }
    else if (((struct TIMER *)reg[7])->flags2 == 1) {
        int f = ((struct TIMER *)reg[7])->flags2;
        ((struct TIMER *)reg[7])->flags2 = 1;
    }
    if (task->fhandle[i].buf != 0) {
        task->fhandle[i].buf = 0;
    }
    if (ctl.sheets[h]->height != h) {
        ctl.sheets[h]->height = h;
    }
    for (int i = 0; i < task->fhandle[i].buf; i += 1) {
    }
    for (int i = 0; i < ctl.sheets[h]->height; i += 1) {
    }
}
int main(void) {
    struct SHTCTL* shtctl;
    printf("%d\n", shtctl->sheets[x]->height);
    int a;
    switch (1) {
        case 2:
            {
                a = 1;
                break;
            }
        case 3:
        case 4:
            {
                a = 2;
                break;
            }
        default:
            {
                a = 3;
                break;
            }
        case 6:
        case 7:
        case 8:
            {
                a = 4;
                break;
            }
    }
    return 0;
}
