# 常量定义

# 默认文件名称
DEFAULT_INPUT_FILE = 'test.py'
DEFAULT_OUTPUT_FILE = 'test.c'

# 支持的文件类型
SUPPORTED_FILE_TYPES = {
    '.py': 'python',
    '.c': 'c'
}

# 默认编译命令
DEFAULT_COMPILE_COMMAND = 'gcc'
DEFAULT_COMPILE_FLAGS = ''

# 错误消息
ERROR_MESSAGES = {
    'MISSING_ARGS': 'Missing required arguments -f and/or -o',
    'UNKNOWN_ARG': 'Unknown argument',
    'UNSUPPORTED_TYPE': 'Unsupported file type',
    'FAILED_PARSE': 'Failed to parse file',
    'COMPILE_FAILED': 'Compilation or execution failed'
}

# 帮助信息
HELP_MESSAGE = '''
Usage: python TransPyC.py -f input_file -o output_file [-wh header_files] [-debug debug_file]
       [-cc compile_command] [-cflags compile_flags] [-run] [-args run_args] [-h helper_files]
       -h: Specify helper files (C or Python) to help identify structs, functions, variables, and pointers
'''

# 类型映射
TYPE_MAP = {
    'CInt': 'int',
    'CChar': 'char',
    'CShort': 'short',
    'CLong': 'long',
    'CFloat': 'float',
    'CDouble': 'double',
    'CVoid': 'void',
    'CUnsigned': 'unsigned',
    'CUnsignedChar': 'unsigned char',
    'CUnsignedInt': 'unsigned int',
    'CUnsignedShort': 'unsigned short',
    'CUnsignedLong': 'unsigned long',
    'CSignedChar': 'signed char',
    'CSizeT': 'size_t',
    'CInt8T': 'int8_t',
    'CInt16T': 'int16_t',
    'CInt32T': 'int32_t',
    'CInt64T': 'int64_t',
    'CUInt8T': 'uint8_t',
    'CUInt16T': 'uint16_t',
    'CUInt32T': 'uint32_t',
    'CUInt64T': 'uint64_t',
    'CIntPtrT': 'intptr_t',
    'CUIntPtrT': 'uintptr_t',
    'CPtrDiffT': 'ptrdiff_t',
    'CWCharT': 'wchar_t',
    'CChar16T': 'char16_t',
    'CChar32T': 'char32_t',
    'CBool': 'bool',
    'CComplex': '_Complex',
    'CImaginary': '_Imaginary',
    'CPtr': '*'
}

# 存储类修饰符
STORAGE_CLASSES = ['static', 'extern']

# 内置函数映射
BUILTIN_FUNCTIONS = {
    'len': 'sizeof',
    'print': 'printf'
}

# 运算符映射
OPERATOR_MAP = {
    'Add': '+',
    'Sub': '-',
    'Mult': '*',
    'Div': '/',
    'Mod': '%',
    'Pow': '**',
    'LShift': '<<',
    'RShift': '>>',
    'BitOr': '|',
    'BitXor': '^',
    'BitAnd': '&',
    'FloorDiv': '/'
}

# 比较运算符映射
COMPARATOR_MAP = {
    'Gt': '>',
    'Lt': '<',
    'GtE': '>=',
    'LtE': '<=',
    'Eq': '==',
    'NotEq': '!=',
    'Is': '==',
    'IsNot': '!='
}

# 一元运算符映射
UNARY_OPERATOR_MAP = {
    'Not': '!',
    'Invert': '~',
    'UAdd': '+',
    'USub': '-'
}

# 复合赋值运算符映射
AUG_OPERATOR_MAP = {
    'Add': '+',
    'Sub': '-',
    'Mult': '*',
    'Div': '/',
    'Mod': '%',
    'Pow': '**',
    'LShift': '<<',
    'RShift': '>>',
    'BitOr': '|',
    'BitXor': '^',
    'BitAnd': '&',
    'FloorDiv': '/'
}

GENERATE_Copyright = r""" /*
                  ___         ___     
      ___        /  /\       /  /\    
     /  /\      /  /::\     /  /:/    
    /  /:/     /  /:/\:\   /  /:/     
   /  /:/     /  /:/~/:/  /  /:/  ___ 
  /  /::\    /__/:/ /:/  /__/:/  /  /\
 /__/:/\:\   \  \:\/:/   \  \:\ /  /:/
 \__\/  \:\   \  \::/     \  \:\  /:/ 
      \  \:\   \  \:\      \  \:\/:/  
       \__\/    \  \:\      \  \::/   
                 \__\/       \__\/    
Copyright© GVSDS Team
Actor TermiNexus

*/
// Generated by TransPyC


"""